name: Test for testjbs branch
on:
  push:
    branches:
      - testjbs

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:3.2
        ports:
          - 27017:27017
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up JDK 11.0.11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.11
      - name: Run local migration
        run: ./gradlew run
